### ISSUE TITLE
wy is may lounar claient on bedrok edision ?

### ISSUE THREAD

**Issue by Asicalug** [Ember-Client/Ember-Client#2]
halp

**Comment by Ember-Client** [comment]
It boots into bedrock because minecraft is currently doing a play bedrock get java and play java get bedrock event so take advantage while you can because you will never own both after its over... yes they are taking your money and making you chose.

**Comment by Asicalug** [comment]
butt ai don laike mincraf bedrok

**Comment by Ember-Client** [comment]
butt daddy mincraf said bdrok is gooood and java bed

**Comment by Asicalug** [comment]
nowww dadi maincraf is wron

**Comment by Ember-Client** [comment]
majopa; sjcraf is aksifplong a olt
